import AppKit
import Combine
import Foundation

@MainActor
final class ClipboardService: ObservableObject, ClipboardProvider {
    @Published private(set) var entries: [ClipboardEntry] = []
    @Published var excludedBundleIDs: [String] {
        didSet { UserDefaults.standard.set(excludedBundleIDs, forKey: "clipboardExcludedBundleIDs") }
    }

    private let pasteboard: NSPasteboard
    private let storeURL: URL
    private let now: () -> Date
    private var lastChangeCount: Int
    private var pollingTimer: Timer?
    private var expirationTimer: Timer?
    private var wakeObserver: NSObjectProtocol?
    private static let defaultExcludedBundles = [
        "com.1password.1password",
        "com.bitwarden.desktop",
        "org.keepassxc.keepassxc",
        "com.apple.Passwords"
    ]
    private let concealedTypes: Set<String> = [
        "org.nspasteboard.ConcealedType",
        "org.nspasteboard.TransientType",
        "org.nspasteboard.AutoGeneratedType"
    ]

    init(
        pasteboard: NSPasteboard = .general,
        storeURL: URL = AppPaths.clipboardStore,
        now: @escaping () -> Date = Date.init
    ) {
        self.pasteboard = pasteboard
        self.storeURL = storeURL
        self.now = now
        excludedBundleIDs = UserDefaults.standard.stringArray(forKey: "clipboardExcludedBundleIDs")
            ?? Self.defaultExcludedBundles
        lastChangeCount = pasteboard.changeCount
        load()
    }

    func start() {
        guard pollingTimer == nil else { return }
        pollingTimer = Timer.scheduledTimer(withTimeInterval: 0.4, repeats: true) { [weak self] _ in
            MainActor.assumeIsolated { self?.poll() }
        }
        RunLoop.main.add(pollingTimer!, forMode: .common)

        if wakeObserver == nil {
            wakeObserver = NSWorkspace.shared.notificationCenter.addObserver(
                forName: NSWorkspace.didWakeNotification,
                object: nil,
                queue: .main
            ) { [weak self] _ in
                MainActor.assumeIsolated { self?.pruneAndSchedule() }
            }
        }
        pruneAndSchedule()
    }

    func stop() {
        pollingTimer?.invalidate()
        pollingTimer = nil
        expirationTimer?.invalidate()
        expirationTimer = nil
        if let wakeObserver {
            NSWorkspace.shared.notificationCenter.removeObserver(wakeObserver)
            self.wakeObserver = nil
        }
    }

    func copy(_ entry: ClipboardEntry) {
        pasteboard.clearContents()
        switch entry.kind {
        case .text, .url:
            pasteboard.setString(entry.payload, forType: .string)
        case .files:
            let urls = entry.payload.components(separatedBy: "\n").map { URL(fileURLWithPath: $0) }
            pasteboard.writeObjects(urls as [NSURL])
        case .image:
            if let data = Data(base64Encoded: entry.payload), let image = NSImage(data: data) {
                pasteboard.writeObjects([image])
            }
        }
        lastChangeCount = pasteboard.changeCount
    }

    func togglePinned(_ id: UUID) {
        guard let index = entries.firstIndex(where: { $0.id == id }) else { return }
        entries[index].isPinned.toggle()
        if ClipboardRetentionPolicy.isExpired(entries[index], at: now()) {
            entries.remove(at: index)
        }
        persist()
        scheduleNextExpiration()
    }

    func delete(_ id: UUID) {
        entries.removeAll { $0.id == id }
        persist()
        scheduleNextExpiration()
    }

    func clear() {
        entries.removeAll { !$0.isPinned }
        persist()
        scheduleNextExpiration()
    }

    func filteredEntries(_ query: String) -> [ClipboardEntry] {
        guard !query.isEmpty else { return entries }
        return entries.filter {
            $0.preview.localizedCaseInsensitiveContains(query)
                || $0.sourceName.localizedCaseInsensitiveContains(query)
        }
    }

    @discardableResult
    func pruneExpired(at date: Date) -> Bool {
        let retained = ClipboardRetentionPolicy.retainedEntries(from: entries, at: date)
        guard retained.count != entries.count else { return false }
        entries = retained
        persist()
        return true
    }

    private func poll() {
        guard pasteboard.changeCount != lastChangeCount else { return }
        lastChangeCount = pasteboard.changeCount
        capture()
    }

    private func capture() {
        let source = NSWorkspace.shared.frontmostApplication
        let bundleID = source?.bundleIdentifier
        guard bundleID != Bundle.main.bundleIdentifier,
              bundleID.map({ !Set(excludedBundleIDs).contains($0) }) ?? true else { return }
        let typeNames = Set((pasteboard.types ?? []).map(\.rawValue))
        guard typeNames.isDisjoint(with: concealedTypes) else { return }

        let sourceName = source?.localizedName ?? "Unknown app"
        if let fileURLs = pasteboard.readObjects(
            forClasses: [NSURL.self],
            options: [.urlReadingFileURLsOnly: true]
        ) as? [URL], !fileURLs.isEmpty {
            let payload = fileURLs.map(\.path).joined(separator: "\n")
            add(kind: .files, preview: fileURLs.map(\.lastPathComponent).joined(separator: ", "), payload: payload, sourceBundleID: bundleID, sourceName: sourceName)
            return
        }

        if let imageData = pasteboard.data(forType: .tiff), imageData.count <= 10_000_000 {
            add(
                kind: .image,
                preview: "Image · \(Formatters.bytes(UInt64(imageData.count)))",
                payload: imageData.base64EncodedString(),
                sourceBundleID: bundleID,
                sourceName: sourceName
            )
            return
        }

        if let text = pasteboard.string(forType: .string)?.trimmingCharacters(in: .whitespacesAndNewlines), !text.isEmpty {
            let kind: ClipboardContentKind = URL(string: text)?.scheme != nil ? .url : .text
            add(kind: kind, preview: String(text.sanitizedSummary.prefix(160)), payload: text, sourceBundleID: bundleID, sourceName: sourceName)
        }
    }

    private func add(kind: ClipboardContentKind, preview: String, payload: String, sourceBundleID: String?, sourceName: String) {
        let captureDate = now()
        _ = pruneExpired(at: captureDate)
        let hash = payload.contentHash
        entries.removeAll { $0.contentHash == hash && !$0.isPinned }
        entries.insert(
            ClipboardEntry(
                id: UUID(),
                kind: kind,
                preview: preview,
                payload: payload,
                sourceBundleID: sourceBundleID,
                sourceName: sourceName,
                createdAt: captureDate,
                isPinned: false,
                contentHash: hash
            ),
            at: 0
        )
        let pinned = entries.filter(\.isPinned)
        let recent = entries.filter { !$0.isPinned }.prefix(100)
        entries = pinned + Array(recent)
        persist()
        scheduleNextExpiration()
    }

    private func load() {
        guard let data = try? Data(contentsOf: storeURL),
              let decoded = try? JSONDecoder().decode([ClipboardEntry].self, from: data) else {
            scheduleNextExpiration()
            return
        }
        entries = decoded
        _ = pruneExpired(at: now())
        scheduleNextExpiration()
    }

    private func pruneAndSchedule() {
        _ = pruneExpired(at: now())
        scheduleNextExpiration()
    }

    private func scheduleNextExpiration() {
        expirationTimer?.invalidate()
        expirationTimer = nil
        guard let nextExpiration = entries
            .filter({ !$0.isPinned })
            .map({ $0.createdAt.addingTimeInterval(ClipboardRetentionPolicy.maximumAge) })
            .min() else { return }

        let interval = max(0.05, nextExpiration.timeIntervalSince(now()))
        expirationTimer = Timer.scheduledTimer(withTimeInterval: interval, repeats: false) { [weak self] _ in
            MainActor.assumeIsolated { self?.pruneAndSchedule() }
        }
        RunLoop.main.add(expirationTimer!, forMode: .common)
    }

    private func persist() {
        do {
            if entries.isEmpty {
                if FileManager.default.fileExists(atPath: storeURL.path) {
                    try FileManager.default.removeItem(at: storeURL)
                }
                return
            }
            try FileManager.default.createDirectory(
                at: storeURL.deletingLastPathComponent(),
                withIntermediateDirectories: true
            )
            let data = try JSONEncoder().encode(entries)
            try data.write(to: storeURL, options: .atomic)
        } catch {
            // Clipboard capture remains usable in-memory if disk persistence fails.
        }
    }
}
